"""
Answer Node with RAG
"""
from typing import Dict, Any, List
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage

from app.utils.logging_config import get_logger
from ..base import BaseNode, State
from app.services.text_store_services import text_store_factory
from app.services.llm import llm_factory, LLMProvider
from ..config.domain_config_manager import get_domain_config_manager

class RAGAnswerOutput(BaseModel):
    """Output schema for RAG answer"""

    text_answer: str = Field(
        description="The final answer generated by the LLM based on the context"
    )
    docs_index: List[int] = Field(
        description="List of document index used to generate the answer"
    )

class RAGAnswerNode(BaseNode):
    """Node that provides answers using RAG with LLM"""

    def __init__(self):
        super().__init__("rag_answer_agent")
        # Get specific logger for this class
        self.logger = get_logger("nodes.chat_nodes.answer_with_rag")
        self.config_manager = get_domain_config_manager()

        try:
            self.logger.info("✅ RAG Answer initialized successfully with domain config")

        except Exception as e:
            self.logger.error(f"❌ Failed to initialize RAG Answer: {str(e)}")
            raise

    def execute(self, state: State) -> Dict[str, Any]:
        """Execute RAG answer logic using LLM"""
        messages = state["messages"]
        current_input = state["current_input"]
        domains = state["domains"]
        if not domains:
            domains = self.config_manager.get_available_domains()
        # Use the first (primary) domain for configuration
        primary_domain = domains[0] if domains else "data_science"
        
        # Get domain-specific configurations
        model_config = self.config_manager.get_model_config(primary_domain, "answer_with_rag")
        prompt_config = self.config_manager.get_prompt_config(primary_domain, "answer_with_rag")

        self.logger.info(f"🔍 Processing RAG answer query: '{current_input}' using domain: '{primary_domain}'")
        self.logger.debug(f"📝 Messages to process: {messages}")

        # Retrieve context from all domains
        context_text = []
        retrieved_doc_refs = []  # Track the actual documents passed into the prompt

        for domain in domains:
            current_docs = []
            try:
                # Use domain name directly as text store name
                text_store_service = text_store_factory.get_store_by_name(domain)
                current_docs = text_store_service.search_documents_by_query(query=current_input)
                
                # Track the actual documents in the same order they are supplied to the model.
                for doc in current_docs:
                    retrieved_doc_refs.append({
                        'domain': domain,
                        'doc_id': doc.metadata.get('doc_id', 'unknown_id'),
                        'raw_text': doc.metadata.get('raw_text', ''),
                    })

                self.logger.debug(f"📄 Retrieved {len(current_docs)} documents from '{domain}' vector store")

                for i, doc in enumerate(current_docs):
                    chunk = f"***CHUNK_{i+1}***\n\n{doc.metadata.get('raw_text', '')}"
                    context_text.append(chunk)
                                  
            except Exception as e:
                self.logger.error(f"❌ Error retrieving documents for domain '{domain}': {str(e)}")
                continue

        # Use domain-specific prompts
        system_prompt = prompt_config.system_prompt
        user_prompt = prompt_config.user_prompt_template.format(
            messages=messages,
            current_input=current_input,
            context_text="\n\n".join(context_text)
        )

        # Prepare messages for LLM
        llm_messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt),
        ]

        self.logger.debug(f"🗨️ System message length: {len(system_prompt)} chars")
        self.logger.debug(f"👤 User message length: {len(user_prompt)} chars")
                                      
        # Use domain-specific model configuration
        answer_llm = llm_factory.get_structured_model(
            LLMProvider[model_config.provider.upper()], 
            RAGAnswerOutput,
            model_name=model_config.model_name,
            method="json_schema", 
            strict=True
        )

        try:
            # Call the LLM with the messages
            response = answer_llm.invoke(llm_messages)     
            answer = response.text_answer

            self.logger.info("📚 RAG answer generated successfully")
            self.logger.debug(f"📝 Response length: {len(answer)} characters")
            
            # DEBUG: Log the full LLM response structure
            self.logger.debug(f"🔍 Full LLM response: {response}")
            self.logger.debug(f"🔍 Response type: {type(response)}")
            self.logger.debug(f"🔍 Response docs_index: {getattr(response, 'docs_index', 'NOT_FOUND')}")
            self.logger.debug(f"🔍 Retrieved doc refs length: {len(retrieved_doc_refs)}")
            
            # Return the actual retrieved documents used to build context.
            # This is more reliable than trusting model-generated source indices.
            used_docs = [
                {"doc_id": doc_ref["doc_id"], "domain": doc_ref["domain"]}
                for doc_ref in retrieved_doc_refs
            ]

            self.logger.info(
                f"📋 Using {len(used_docs)} retrieved documents across domains: "
                f"{set(doc['domain'] for doc in used_docs) if used_docs else 'None'}"
            )
            
            return {
                "text_answer": answer,
                "used_docs": used_docs
            }

        except Exception as e:
            self.logger.error(f"❌ Error generating RAG answer: {str(e)}")
            fallback_answer = "I found relevant material, but the model service is busy right now. Please try again shortly."
            return {
                "text_answer": fallback_answer,
                "final_answer": fallback_answer,
                "used_docs": [],
            }
        
answer_with_rag = RAGAnswerNode()
